/* Autogenerated by hxtools bin2c */
#ifndef SPLASH_H
#define SPLASH_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_splash_cropped_bmp[39478];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* SPLASH_H */
